services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak-security-lab
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
